spring:
  application:
    name: zuul-demo
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://lixf:lixf@localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
zuul:
  routes:
    eureka-client-user:
      path: /user/**
  retryable: true
