spring:
  application:
    name: eureka-server
  security:
    user:
      name: lixf
      password: lixf
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
